openapi: 3.0.3
info:
  title: User Management API
  version: 1.0.0
servers:
  - url: http://localhost:8090/autify
    description: Optional server description, e.g. Internal staging server for testing
tags:
  - name: user
    description: Operations for user.
  - name: role
    description: Operations for role.
paths:
  /users:
    $ref: './paths/users.yml'
  /users/{userId}:
    $ref: './paths/user.yml'
  /roles:
    $ref: './paths/roles.yml'
  /role/{roleId}:
    $ref: './paths/role.yml'
components:
  schemas:
    $ref: './schemas/_index.yml'
