openapi: 3.0.3
info:
  title: User Management API
  version: 1.0.0
servers:
  - url: http://localhost:8090/autify
    description: Optional server description, e.g. Internal staging server for testing
tags:
  - name: user
    description: Operations for user.
paths:
  /users:
    post:
      tags:
        - user
      operationId: createUser
      summary: Add a new user
      requestBody:
        description: User object to be added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User added successfully
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input, user not added
        '500':
          description: Application Internal Error
    put:
      tags:
        - user
      operationId: updateUser
      summary: Update existing user
      requestBody:
        description: User object to be added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/User'
  /users/{userId}:
    delete:
      tags:
        - user
      summary: Delete user
      description: This can only be done by the logged in user.
      operationId: deleteUser
      parameters:
        - name: userId
          in: path
          description: The id that needs to be deleted
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '404':
          description: User not found.
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        password:
          type: string
      required:
        - name
        - email
        - password
