openapi: 3.0.3
info:
  title: User Management API
  version: 1.0.0
tags:
  - name: user
    description: Operations for users
paths:
  /api/v1/users:
    post:
      tags:
        - user
      operationId: createUser
      summary: Add a new user
      requestBody:
        description: User object to be added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User added successfully
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input, user not added
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        password:
          type: string
      required:
        - name
        - email
        - password
