openapi: 3.0.0
info:
  title: Hello World API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Returns a greeting message
      operationId: getGreeting
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string